<?php

namespace ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
     * Loads the latest built products
     *
     * @return Product[]
     */
    public function findRecentLatestProducts()
    {
        $qb = $this->createQueryBuilder('product');

        return $qb
            ->orderBy('product.additionDate', 'DESC')
            ->setMaxResults(25)
            ->getQuery()
            ->getResult()
        ;
    }
}
